publishDir = "docs"
baseURL = "https://alee0001.github.io/"
languageCode = "en-us"
paginate = 6
theme = "portio-hugo"
title = "Alex Lee"
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "Portfolio"
url = "#blog"
weight = 2
[[menu.main]]
name = "About"
url = "#about"
weight = 3



# Sitemap Menu
[[menu.sitemap]]
name = "Back to the beginning"
url = "#home"
weight = 1

[params]
contactLink = "contact"
copyright = "Built with Portio-Hugo Template"
footerLogo = "images/contact/logo - footer.png"
logo = "images/site-navigation/logo.png"

[params.address]
address = "Hershey, Pennsylvania United States"
email = "alexmize@my.unt.edu"
openingHours = "10:00 AM - 5:00 PM"
phone = "+(1) 832 795 6031"

# Social icons

[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/in/alex-lee-776a39b7/"
weight = 2
[[params.social]]
icon = "fa-github-square"
url = "https://github.com/ALEE0001"
weight = 3

